name: Fence Tests and Build Pipeline

# Define when the workflow should run
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

# Define global environment variables
env:
  PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Secrets are stored in GitHub Secrets
  GOOGLE_GEMINI_API_KEY: ${{ secrets.GOOGLE_GEMINI_API_KEY }}
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

# Define jobs to run in the workflow
jobs:
  # Job for running tests
  test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies using uv
        run: uv sync

      - name: Run tests
        run: uv run pytest tests --junitxml=fence/tests/report.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: fence/tests/report.xml

  # Job for building the package
  build:
    name: 📦 Build package
    runs-on: ubuntu-latest
    needs: test # Only run if the test job passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies using uv
        run: uv sync

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
          retention-days: 7
