name: Fence publish Pipeline

# Manually trigger required
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi-release
      url: https://pypi.org/project/fence-llm/
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies using uv
        run: uv sync

      - name: Run tests
        run: uv run pytest tests

      - name: Build package
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
